#!/bin/bash
# Purpose : Connect to linux server in RML                  
# Author  : Tin Tran                     

#---------------------------------------------------------------
# Check variable is interger or not
#----------------------------------------------------------------
function is_integer() {
  printf "%d" $1 > /dev/null 2>&1
  return $?
}

#---------------------------------------------------------------
# Format view
#----------------------------------------------------------------
function format() {
  printf "%s\n" "_________________________________________________________"
  printf "%s\n" "                                                 "
  printf "%s\n" "* Having ${#ip[@]} matching results, choose 1 in ${#ip[@]}"
  printf "%s\n\n" "_________________________________________________________"
}

#---------------------------------------------------------------
# Define variable
#----------------------------------------------------------------
path="./List_server_ip_public"
ip=(`grep "$1" $path | awk '{print $1}'`)
server=(`grep "$1" $path | awk '{print $2}'`)
key=(`grep "$1" $path | awk '{print $3}'`)

echo $server

#---------------------------------------------------------------
# Main
#----------------------------------------------------------------
# Check if having more selections
u_ma="ubuntu"

if [ ${#server[@]} -ge 1 ];then
  format
  j=0
  for i in "${server[@]}"; do
    let "count=$j+1"
    #printf "%s\t\t\t%s\t%s\n" "[$count] - $i" "${ip[$j]}" "${key[$j]}"
    if [[ "$count" -le 9 ]]; then
      count="0$count"
    else
      count="$count"
    fi

    printf "%s %15s %30s %s\n" "[$count] - " "${ip[$j]}" "${key[$j]}" "$i"
    let "j=$j+1"
  done
  printf "%s\n\n" "_________________________________________________________"

  # Choose server to connect
  echo -n "* Which server: "; read input
  lenght=${#ip[@]}
  # Check if it is not interger
  if is_integer $input;then
    for (( i=1; i <= $lenght; i++ )); do
      if [ $input -eq $i ];then
        let "j=$i-1"
        echo ":: Connecting server ${server[$j]} ${ip[$j]} ..."
        ssh -i "./key_pem/${key[$j]}" $u_ma@"${ip[$j]}"
      fi
    done
  else
    printf "%s\n\n" "_________________________________________________________"
    printf "%s\n\n" "[WARNING] - Wrong selection. Try again or go home"
  fi
else
  echo ":: Your choice is not supported"
fi
